import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const wrapperStyles = `slds-grid slds-wrap ${styles.wrapper}`;

  return (
    <div className={wrapperStyles}>
      <Head>
        <title>PTS - POC with Next.JS</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <nav className='slds-col'>
        <ul>
          <li>
            <Link href='/'>
              <a>Trust</a>
            </Link>
          </li>
          <li>
            <Link href='/incidents'>
              <a>Incidents</a>
            </Link>
          </li>
          <li>
            <Link href='/general'>
              <a>General</a>
            </Link>
          </li>
        </ul>
      </nav>

      <main className='slds-col slds-card slds-p-around--xx-large'>
        Hello, again!
      </main>

      <footer className='slds-grid slds-grid_vertical slds-grid_vertical-align-center slds-p-vertical_medium'>
        Footer Text
      </footer>
    </div>
  );
};

export default Home;
